apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: argocd
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
